apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-deployment
  labels:
    app: quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes
  template:
    metadata:
      labels:
        app: quotes
    spec:
      containers:
      - name: quotes
        image: quotes-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9002
        env:
          - name: MYSQL_URI
            valueFrom:
              secretKeyRef:
                name: app-sercrets
                key: mysql_uri 
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: app-sercrets
                key: jwtSecretKey
---
apiVersion: v1
kind: Service
metadata:
  name: quotes-service
spec:
  type: LoadBalancer
  selector:
      app: quotes
  ports:      
    - name: http
      protocol: TCP
      port: 9002
      targetPort: 9002